### ISSUE TITLE
Datamodel ERD

### ISSUE THREAD

**Issue by kasp470f** [kasp470f/1semester#7]

**Comment by NCBR** [comment]
S. 227 i grøn bog

**Comment by kasp470f** [comment]
6dfbdae88a1c8c4ba1d2aa5072f224455d0b33df

**Comment by NCBR** [comment]
6dfbdae88a1c8c4ba1d2aa5072f224455d0b33df
Added ERD model, that shows relationship between Entities with Modality and Cardinality
