### ISSUE TITLE
Hvad skal indikatoren gå af på?

### ISSUE THREAD

**Issue by kasp470f** [kasp470f/1semester#83]

**Comment by keemaun** [comment]
Vi blev enige om at sætte indikatoren baseret på valgte kommunes positiv procent data i forhold til antal smittede, som vi har sat til at skille på 2%, da det efter SSI er covid-19's umiddelbare smitte procent, og derfor hvis den overstiger 2% vil der anbefales restriktioner. Indikatoren er sat til 3 forskellige style triggers, en der fortæller dig at du ikke har valgt kommune hvis ikke det er valgt, en der siger alt ok, hvis positiv procenten er under 2%, en der siger restriktioner er anbefalet hvis den er over 2%.
